name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Clone main repo
      - name: Login to GitHub Container Registry # login to get container image
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # jaar GH shey owner - me
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # everything in the current directory
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Update GitOps repository # update to trigger CD
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }} # manipulate the GitOps repo
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # --- Clone repository using HTTPS URL without token
          git clone https://github.com/NNafis-007/gitops-demo.git gitops
          cd gitops
          
          # --- UPDATES THE IMAGE NAME in deployment.yaml (of gitops repo) -> TRIGGERS CD
          if [[ "$OSTYPE" == "darwin"* ]]; then 
            sed -i '' "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          else
            sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" deployment.yaml
          fi
          
          # Commit changes -> will trigger CD
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          git push -f https://${GIT_TOKEN}@github.com/NNafis-007/gitops-demo.git main